
// This file was auto-generated by ML.NET Model Builder. 

using MLNET_Console_App;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
// var imageBytes = File.ReadAllBytes(@"D:\Defects\images\crease\img_01_3436789500_00004.jpg");
// var imageBytes = File.ReadAllBytes(@"D:\Defects\images_test\water_spot\img_01_424995500_00255.jpg");

var imageBytes = File.ReadAllBytes(@"C:\Projects\MLNET_NET_Core\ML_Data\ML_check\punching_hole\img_02_425507200_00018.jpg");

MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    ImageSource = imageBytes,
};

Dictionary<int, float> data = new Dictionary<int, float>();


// Make a single prediction on the sample data and print results.
var predictionResult = MLModel.Predict(sampleData);

Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel}");

foreach (var score in predictionResult.Score)
{
    Console.WriteLine(score);
}

// 0 water_spot

//$"" +
//$"" +
//$"Predicted Label scores: [{String.Join(",", predictionResult .Score)}]\n\n");
